#!/usr/bin/env bash

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/game-launcher"
config_file="$config_dir/launcher.conf"

custom_games_file="$config_dir/custom-games.conf"
game_stats_file="$config_dir/game-stats.conf"

# default settings
gog_games_path="$HOME/GOG Games/"
steamapps_path="$HOME/.local/share/Steam/steamapps"
game_stats="on"

# game array format:
# Type|Game Name|Type Flags|Arguments
# Types:
# exec  = executable
# steam = steamid
games=()

# sorted game list
sorted_games=()

function source_config()
{
    if [ -f "$config_file" ]
    then
        source "$config_file"
    fi
}

function get_games()
{
    get_gog_games
    get_steam_games
    get_custom_games

    if [ ! "${games[0]}" ]
    then
        return 1
    fi
}

function get_gog_games()
{
    if [ ! -d "$gog_games_path" ]
    then
        return
    fi

    local game_name

    # get games
    for game in "$gog_games_path"/*
    do
        # found the game
        if [ -f "$game/start.sh" ] && \
            [ -f "$game/gameinfo" ]
        then
            game_name="$(head -1 "$game/gameinfo")"
            games+=("exec|$game_name|$game/start.sh")
        fi
    done

}

# returns item
function steam_appmanifest_get()
{
    file="$1"
    item="$2"

    grep "$item" "$file" \
        | sed -e 's/^[ \t]*//' \
        | cut -d'"' -f4 
}

function get_steam_games()
{
    local game_name game_appid

    if [ ! -d "$steamapps_path" ]
    then
        return
    fi

    # get all appmanifest files
    for appmanifest in "$steamapps_path"/appmanifest_*
    do
        game_name="$(steam_appmanifest_get "$appmanifest" "\"name\"")"
        game_appid="$(steam_appmanifest_get "$appmanifest" "\"appid\"")"

        if [ ! "$game_name" ] || \
            [ ! "$game_appid" ]
        then
            continue
        fi

        # add game to list
        games+=("steam|$game_name|$game_appid")
    done
}

function get_custom_games()
{
    local game_name game_exec game_args

    if [ ! -f "$custom_games_file" ]
    then
        return
    fi

    while IFS='' read -r line
    do
        if [[ "$line" = "#"* ]]
        then
            continue
        fi

        game_name="$(echo "$line" | cut -d'|' -f1)"
        game_exec="$(echo "$line" | cut -d'|' -f2)"
        game_args="$(echo "$line" | cut -d'|' -f3)"

        if [  "$game_name" ] && \
            [  "$game_exec" ]
        then
            games+=("exec|$game_name|$game_exec|$game_args")
        fi
    done < "$custom_games_file"
}

function sort_games()
{
    IFS=$'\n' sorted_games=($(sort <<<"${games[*]}"))
    unset IFS
}

function show_menu()
{
    local game_names game_length

    game_length="${#sorted_games[@]}"
    i=1
    # build game_names array
    for item in "${sorted_games[@]}"
    do
        # don't append newline on last game item
        if [ "$i" = "$game_length" ]
        then
            game_names+="$(echo "$item" | cut -d'|' -f2)"
        else
            game_names+="$(echo "$item" | cut -d'|' -f2)\n"
        fi
        ((i++))
    done

    if [ ! "$rofi" ]
    then
        rofi="rofi"
    fi

    game_id="$(echo -e "${game_names[@]}" | "$rofi" -dmenu -p game -format i -i)"
}

function save_time()
{
    local game_name duration saved_duration

    duration="$1"
    game_name="$(echo "${sorted_games[$game_id]}" | cut -d'|' -f2)"

    if (( "$duration" < 60 ))
    then
        return
    fi

    if [ ! -f "$game_stats_file" ]
    then
        echo "$game_name|$duration" > "$game_stats_file"
    else
        if [ "$(grep "$game_name" "$game_stats_file")" ]
        then
            saved_duration="$(grep "$game_name" "$game_stats_file" | cut -d'|' -f2)"
            
            if duration="$(($saved_duration + $duration))"
            then
                sed -i "s@$game_name|$saved_duration@$game_name|$duration@g" \
                        "$game_stats_file"
            fi
        else
            echo "$game_name|$duration" >> "$game_stats_file"
        fi
    fi
    
}


# Measure time
function measure_exec()
{
    local file args exec_duration

    file="$1"
    shift
    args="$@"
    
    SECONDS=0

    "$file" $args
    
    exec_duration="$SECONDS"
    
    if [ "$game_stats" = "on" ]
    then
        save_time "$exec_duration"
    fi
}

function launch_game_exec()
{
    file="$(echo "${sorted_games[$game_id]}" | cut -d'|' -f3)"
    args="$(echo "${sorted_games[$game_id]}" | cut -d'|' -f4)"

    
    measure_exec "$file" $args
}

function launch_game_steam()
{
    appid="$(echo "${sorted_games[$game_id]}" | cut -d'|' -f3)"
    
    measure_exec steam -silent "steam://rungameid/$appid"
}

function launch_game()
{
    game_type="$(echo "${sorted_games[$game_id]}" | cut -d'|' -f1)"

    case "$game_type" in
        "exec") launch_game_exec;;
        "steam") launch_game_steam;;
    esac
}

source_config

if ! get_games
then
    echo "Failed to get games"
    exit 1
fi

sort_games

show_menu

if [ ! "$game_id" ]
then
    echo "Failed to get game id"
    exit 1
fi

launch_game
