#!/usr/bin/env bash

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/game-launcher"
custom_games_file="$config_dir/custom-games.conf"

function usage()
{
    echo "$0 \"[game name]\" \"[game command]\" \"[game arguments]\""
    exit
}

if [ ! "$2" ]
then
    usage    
fi

if [ ! -d "$config_dir" ]
then
    mkdir -p "$config_dir"
fi

game_name="$1"
game_command="$2"
game_arguments="$3"

if [ ! -f "$game_command" ] && \
    ! command -v "$game_command" &> /dev/null
then
    echo "Invalid game command"
    usage
    exit 1
fi

echo "$game_name|$game_command|$game_arguments" >> "$custom_games_file"
